---
version: '3'

tasks:
  build:
    desc: Build package
    cmds:
    - uv build

  mypy:
    desc: Run mypy checker
    cmds:
    - uv run mypy ipx800/ tests/

  pylint:
    desc: Run pylint linter
    cmds:
    - uv run pylint ipx800/ tests/

  ruff:
    desc: Run ruff checker
    cmds:
    - uv run ruff check ipx800/ tests/

  test:
    desc: Run tests with pytest
    cmds:
    - uv run ruff check ipx800/ tests/

  validate:
    desc: Run all validators
    cmds:
    # - task: mypy
    # - task: pylint
    - task: ruff
