---
version: '3'

tasks:
  build:
    desc: Build package
    cmds:
    - uv build --clear
    - uv run --isolated --no-project --with dist/*.whl --with pytest pytest
    - uv run --isolated --no-project --with dist/*.tar.gz --with pytest pytest

  mypy:
    desc: Run mypy checker
    cmds:
    - uv run mypy

  pylint:
    desc: Run pylint linter
    cmds:
    - uv run pylint

  ruff:
    desc: Run ruff checker
    cmds:
    - uv run ruff check

  test:
    desc: Run tests with pytest
    cmds:
    - uv run pytest

  validate:
    desc: Run all validators
    cmds:
    # - task: mypy
    # - task: pylint
    - task: ruff
